spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cgv?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Wnsqja6602@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0  # 기본 DB
      timeout: 2000ms


  main:
    allow-bean-definition-overriding: true


logging:
  level:
    org.springframework.data.redis.core: DEBUG
    org.springframework.data.redis.connection: DEBUG


tmdb:
  api-key: "c3d8374f328df623ba0cc4e206ce419c"

iamport:
  api-key: "6076478676482455"
  api-secret: "QUT74sG300lVDbvjt0Qj4w4t6blVwfFsxhzBVfVZV5KnF5Hqyd5Gko156K33U7YqlQkpOmYDKAHZMbm7"